---

- name: Retry a job
  ansible.builtin.uri:
    url: "https://gitlab.com/api/v4/projects/{{ gitlab_project_id }}/jobs/{{ item.id }}/retry"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_token }}"
    status_code:
      - 201
  register: gitlab_job_retry
  loop: "{{ gitlab_job.json }}"
  loop_control:
    label: "{{ item.id }}: {{ item.name }} ({{ item.status }})"
  when:
    - item.status == "failed"
  changed_when:
    - gitlab_job_retry.status == 201
